kumuluzee:
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  nats:
    response-timeout: PT5S
    servers:
      - name: default
        addresses:
          - nats://localhost:4222
      - name: secure-unverified-client
        addresses:
          - tls://localhost:4223
          - opentls://localhost:4223
        tls:
          trust-store-path: certs\truststore.jks
          trust-store-password: password2
      - name: secure
        addresses:
          - tls://localhost:4224
        tls:
          trust-store-path: certs\truststore.jks
          trust-store-password: password2
          key-store-path: certs\keystore.jks
          key-store-password: password